### ISSUE TITLE
Database and Change Management for Initial Data Storage

### ISSUE THREAD

**Issue by benrick** [DevChatter/Smilodon#17]
**Is your feature request related to a problem? Please describe.**
To start implementing the WebFinger and ActivityPub specifications, we'll need to be able to store data.

**Describe the solution you'd like**

1. Check for SQLite database on application load. If it's missing, create the database with a table for the version or schema.
2. Check if we need a version update and update the schema if required.
3. If tables are empty, load some sample data.

**Additional context**
We might consider using FluentMigrator or some other Database Change Management tool. Alternately, we could maintain just a working database that we overwrite when we need an update.

**Comment by edmistond** [comment]
This is a slightly less common suggestion, but what about [DbUp](https://dbup.readthedocs.io/en/latest/)? We used a customized version of it very successfully at my previous job, it supports MSSQL, Postgres, and SQLite, and it's just straight up SQL files, no weird DSLs. The major downside is supporting multiple DBs would require multiple sets of SQL.

I have a sample project from when I was evaluating it about two years ago: https://gitlab.com/edmistond/dbuptesting

**Comment by benrick** [comment]
Yeah, I'd be fine with that for database change management tool. I think I've used it before. I've used so many database change management tools at this point.

**Comment by kirkbrauer** [comment]
@edmistond that's an interesting suggestion. I've never used that, most of my experience is just with EF Core migrations, which tend to be a bit more cross-platform and similar to RoR's implementation, but I'm open to anything lighter like Dapper.

**Comment by benrick** [comment]
DbUp is similar to the database change management tools I used back in the
'00s. I'm on board. I like simplicity for these.

**Comment by kirkbrauer** [comment]
@benrick I think this game plan checks out. If we use EF Core we can also load data using their [Data Seeding](https://learn.microsoft.com/en-us/ef/core/modeling/data-seeding) feature. That would allow us to automatically load static data during a migration. We could also just run some transactions using whichever ORM on load for test data.

**Comment by benrick** [comment]
Sounds good. Who wants to put a PR together?

**Comment by edmistond** [comment]
I'm a bit weaker on EF Core setup so I suspect you folks have a better handle on what the current best practices are, but I'm happy to review once it's ready. :)

**Comment by kirkbrauer** [comment]
@benrick @edmistond I can take a crack at it if you want. I'll start with an infrastructure project and go from there.

**Comment by benrick** [comment]
Go for it.

**Comment by kirkbrauer** [comment]
@benrick do you want this to be a Postgres DB, or stick with SQLite? I have Npgsql installed now, but I can swap to the SQLite equivalent, which I think is just called `Microsoft.EntityFrameworkCore.Sqlite`. Right now, things should be the same, but the schema types might diverge quickly because of SQLite's quirks.

**Comment by kirkbrauer** [comment]
Also, @benrick @edmistond how do we want to separate the API models vs the persisted entity models? 

Mastodon takes the approach of having [one giant schema file](https://github.com/mastodon/mastodon/blob/main/db/schema.rb) hat has all the entities defined directly. EF Core is a bit more flexible about this, but I think the easiest way to do it is to create the domain model classes and make those mirror the DB. On the other hand, the API responses can be records, that way these two are not coupled and can evolve independently of each other like in the original Mastodon. We can use something like AutoMapper to map between these models where necassary.

**Comment by edmistond** [comment]
That approach works for me. I haven't used records in C# aside from kicking the tires a little, so I'm pretty interested to get into them. I think I would probably start with creating the entity classes (maybe using the EF tooling after applying that schema to a blank db, because I am lazy) and then we can add records as needed as we build individual pieces.

Thanks for finding that schema file, though - I hadn't noticed it when poking around and I was doing some research to see if we could get Rails' db migrations to generate something like that.

That schema file is a great starting point for DbUp migrations, incidentally. You could add the whole script as the first migration and then start applying individual changes on top of that.

As for AutoMapper... I've used it at multiple jobs/clients now. It's great software _except_ when it's a major culprit in being up until 3am fixing a broken deploy. 😂 The good news is that you can avoid the particular problem we hit by making sure your tests run `AssertConfigurationIsValid` to make sure you didn't break a config.

**Comment by kirkbrauer** [comment]
@edmistond yeah, I think records are the best way to DTOs, much cleaner syntax and they're automatically serializable to JSON, which is pretty much perfect.

As for AutoMapper, I like using it but I agree that you need some validation. I've gotten into the habit of unit testing my mappings to ensure that the configuration is valid and actually behaves as intended.

I'm going to try to apply that migration using RoR and see if I can use EF Core's reverse engineering features to generate all the entity classes automatically.

**Comment by benrick** [comment]
Regarding API models, yes, records were basically built for being the DTO objects returned by APIs, etc. There's some nuance to applying attributes to properties. See the example classes I have in here already.

Regarding database type, let's jump straight to postgres. Starting from the mastodon schema is the perfect first migration for DbUp to make us compatible with their system, but you can skip it to get the classes created first if you prefer.

And yes, Automapper without `AssertConfigurationIsValid` is just asking for trouble, and you can still have problems even when that passes.

Let's try to have our model objects not know about EF if we can, so that we only need the Domain Models and the API models.

**Comment by edmistond** [comment]
@benrick Sounds good. If we want to go with DbUp, then unless something has changed in the last ~2 years, we will need some kind of hook in the code to execute the migration process. We can probably hack that into application startup somehow, or we can make it be a separate CLI app.

I would personally favor the latter, because the idea that my database schema might get modified just by starting up the main web application scares me... but I am very conservative about this sort of thing. If we do a CLI app I would just have it take a connection string, and maybe use an environment variable as well. I suspect that's getting into a whole new "how are we gonna do configuration management" issue that we haven't created yet. 😄

**Comment by kirkbrauer** [comment]
@edmistond Yeah totally, I also don't think running the migrations on startup is a good long-term solution. The way I've been doing it in my projects is checking if there is a "--migrate" argument, and the running migrations only when that is present.

In my current deployment setup, we use Kubernetes jobs that use the same exact container as prod, but we start with the migrate flag. When the migration completes, the program exits and the job is complete. After that completes, it triggers the deployment of the actual pods.

**Comment by kirkbrauer** [comment]
Ok, I have successfully run the Ruby migrations on my local machine for mastodon. I now have a local database with the Mastodon schema installed. I'm now going to attempt to reverse-engineer it using EF Core, wish me luck!

**Comment by kirkbrauer** [comment]
Quick update on the EF Core migration -- I was able to reverse-engineer everything using `dotnet ef dbcontext scaffold`. There is a bout with EF Core 7, which causes it to not understand entities without a primary key defined in the DB, which for whatever reason Mastodon has a lot of. I had to temporarily downgrade to EF Core 6 to run the scaffold and then manually upgrade the generated entities and packages. Also, for some reason, EF Core does not respect certain DB naming conversations, so I had to manually define the index and primary key names. I'll submit a PR as soon as the basic InitialCreate migration produces something similar to the original schema.

We might want to make a GitHub Actions Workflow that clones the original mastodon repo and runs their migrations and then compares our schema against theirs to ensure compatibility. If we decide to not actually have full DB compatibility, then we can probably safely ignore that suggestion 😊.
